### ISSUE TITLE
[Commercial] Licence

### ISSUE THREAD

**Issue by victor-a-rigacci** [nanoexpress/pro#1]
Hello,  how i purchase the licence for a commercial closed project?
Thanks!

**Comment by dalisoft** [comment]
Hello and thanks for interest. 
See https://github.com/nanoexpress/pro/blob/master/README.md#license

TLDR: When you become sponsor via Patreon, you can use nanoexpress Pro/Slim on your closed source applications. 
Also your or your company  name will be shown in Sponsors section
