### ISSUE TITLE
Crash randomly..

### ISSUE THREAD

**Issue by MrBot45** [nanoexpress/pro#133]
### Is you/your team sponsoring this project

- [ ] Yes
- [x] No

### Minimal reproducible repo

Link here

### Current Behavior

Crash on POST request.
TypeError: stream.on is not a function
    at readStream (/root/middleware/node_modules/raw-body/index.js:190:10)
    at getRawBody (/root/middleware/node_modules/raw-body/index.js:108:12)
    at read (/root/middleware/node_modules/body-parser/lib/read.js:77:3)
    at urlencodedParser (/root/middleware/node_modules/body-parser/lib/types/urlencoded.js:116:5)
    at /root/middleware/node_modules/nanoexpress-pro/cjs/nanoexpress.js:1718:17
    at new Promise (<anonymous>)
    at middleware (/root/middleware/node_modules/nanoexpress-pro/cjs/nanoexpress.js:1717:22)
    at handler (/root/middleware/node_modules/nanoexpress-pro/cjs/nanoexpress.js:1910:40)

### Expected behavior/code

Allow users to login.

### Environment

- Node/npm version: Node js 14.15.0
- OS: Ubuntu 18.04

### Additional context/Screenshots

Add any other context about the problem here. If applicable, add screenshots to help explain.

### Note

- **Project is provided as-is without any support nor warranty**
- **If this issue not related to this project and exists on [core](https://github.com/uNetworking/uWebSockets.js) of this project, please close issue or not open**

**Comment by dalisoft** [comment]
Hi @MrBot45 
Thanks for trying out nanoexpress and i'm happy to help here to you, but should create minimal reproducible repo to test.

**Comment by MrBot45** [comment]
What do you mean?

**Comment by MrBot45** [comment]
Im using nanoexpress as a middleware proxy. It has a lot of bugs but I can't get this one to work. It seems like the internal fails.

**Comment by MrBot45** [comment]
Go on this page to get the error: https://bobuxpvp.tk/login

Enter anything, it always throw an error. It work fine with express so im not sure what's the issue.

**Comment by dalisoft** [comment]
> What do you mean?

Minimal reproducible repository and/or example, read [here](https://en.wikipedia.org/wiki/Minimal_working_example) to test and fix.



> Im using nanoexpress as a middleware proxy. It have a lot of bugs but I can't find a solution around for this bug. It seems like the internal fails.

Please create separate issue for every bug, i'll look and fix as i can. Also, please don't use nanoexpress as a middleware, just use as Server framework without other frameworks :)

**Comment by dalisoft** [comment]
> Go on this page to get the error: https://bobuxpvp.tk/login
> 
> Enter anything, it always throw an error. It work fine with express so im not sure what's the issue.

I see, but i need MRE/MRR to test and know where it fails and fix.

**Comment by MrBot45** [comment]
Idk how to reproduce the issue.. It's just a reverse proxy..

**Comment by dalisoft** [comment]
> Idk how to reproduce the issue.. It's just a reverse proxy..

Thanks for describe how you use. Do you using **proxy** ([example](https://github.com/nanoexpress/pro/blob/master/examples/proxy.js)) define to use as `reverse proxy`?

**Comment by MrBot45** [comment]
No. My project has over 2k lines of code it's hard to provide a minimal example. It require extenal database and stuff. 

`this.app = nanoexpress();
		
		this.app.setErrorHandler((e, r, s) => {
			console.log(e.stack);
			s.json({error: e.stack});
		}); 
this.app.any('/*', async (req, res) => { // cant use async for no reason so had to make a custom next function because this never return a "next" parameter
			this.process(req, res, () => {
				this.next(req, res);
			});
		});

//Method process
proxy(`${await this.getEndPoint(host)}${reqUrl}`, {
				proxyErrorHandler: (err, res, next) => {
					console.error('Endpoint errored! Status code:', err);
					res.status(507).end(this.errorPage.replace('"Origin"', host || 'unknown host'));
				}
			})(req, res, next);

// Proxy.js

Please fix your write stream they are buggy. I cant get video streaming to work normaly so i had to create my own write stream
let dest = new Stream();
		dest.writable = true;
		dest.byteLength = 0;
		dest.finalSize = 0;
		dest.start = Date.now();
		dest.chunks = [];
		dest.write = (chunk) => {
			try {
				if(g) clearTimeout(g);
				let chunk_ = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
				
				dest.byteLength += chunk_.byteLength;
			
				if(dest.finalSize > 15000000) {
					res.write(chunk_);
				} else {
					dest.chunks.push(chunk_);
				}
			} catch(e) {
				console.log(e);
			}
		}
		
		dest.end = () => {
			console.log('Took ' + (Date.now() - res.startTime) + 'ms', 'Stream end. Bytes:', dest.byteLength, url, dest.finalSize, dest.chunks.length, dest.finalSize > 15000000);
			
			try {
				if(dest.finalSize > 15000000) {
					res.end('');
				} else {
					res.end(Buffer.concat(dest.chunks));
				}
			} catch(e) {
				console.log(e);
			}
			dest.chunks = [];
		}
		
		res.onAborted((e) => {
			console.log('Aborded', url);
			dest.chunks = [];
			errored = true;
		});

let proxiedReq = http.request(options, (res_) => {
			res.cork(() => {
				if(errored) return;


// [...]

if(!errored) res_.pipe(dest);

} [...]`

**Comment by dalisoft** [comment]
Seems your `proxy` function as middleware working wrong.
```diff
Crash on POST request.
TypeError: stream.on is not a function
+ at readStream (/root/middleware/node_modules/raw-body/index.js:190:10)
+ at getRawBody (/root/middleware/node_modules/raw-body/index.js:108:12)
+ at read (/root/middleware/node_modules/body-parser/lib/read.js:77:3)
+ at urlencodedParser (/root/middleware/node_modules/body-parser/lib/types/urlencoded.js:116:5)
at /root/middleware/node_modules/nanoexpress-pro/cjs/nanoexpress.js:1718:17
at new Promise ()
at middleware (/root/middleware/node_modules/nanoexpress-pro/cjs/nanoexpress.js:1717:22)
at handler (/root/middleware/node_modules/nanoexpress-pro/cjs/nanoexpress.js:1910:40)
```

Before **nanoexpress** these modules are crashing, so checkout **proxy** define to make proxy easier and high-performant.

Thanks

**Comment by MrBot45** [comment]
Will check it out, can you try to fix the write stream? I have to make a check for the buffer size to see if it's smaller than 15mb or it's just abordning everytime. Even with this bypass, it's flooding the logs with 

Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse

**Comment by MrBot45** [comment]
The stream end itself while writing data.

**Comment by dalisoft** [comment]
@MrBot45 
Then you using `async` or `stream` wrong.

As issue creation requires 
> If this issue not related to this project and exists on core of this project, please close issue or not open

core of this project does not handle these wraps, but nanoexpress does, but it does not mean it does all magic like express, that's why expressjs almost 8x slower than nanoexpress.

My library isn't great, but you should first checkout examples folder as available some examples how do something correctly.
As it's your code issue, i should close issue and then continue in **closed** status.

If you need premium contact support to fix this, then contact to me via dalisoft@mail.ru or at [Telegram](https://t.me/dalisoft)

**Comment by MrBot45** [comment]
Is it possible to add a next function to setErrorHandler?

**Comment by dalisoft** [comment]
Yep, it is possible. But always you can use 3 argument, not 4. Check examples and documentations please
