### ISSUE TITLE
UnhandledPromiseRejectionWarning in cjs/Route.js

### ISSUE THREAD

**Issue by reyzvikh** [nanoexpress/pro#21]
If a route handler that returns a promise throws an error, UnhandledPromiseRejectionWarning occurs in the cjs/Route.js file.

![image](https://user-images.githubusercontent.com/61026842/77088989-e8bc6000-6a0d-11ea-9260-7791211f5c9c.png)

The error thrown by a route handler wouldn't be processed by a specified error handler, and the request gets stuck.

You can reproduce this issue by running [this example](https://github.com/reyzvikh/nanoexpress-error-example)
Provided example uses the nanoexpress-pro@1.10.11

**Comment by dalisoft** [comment]
@reyzvikh Hi and thanks for report.

Can you please check this example with `nanoexpress-pro@1.1.0.13`?

**Comment by dalisoft** [comment]
Issue was fixed in `v1.10.13`, if issue occurs again, feel free to re-open issue or create another issue
