### ISSUE TITLE
HTTP Pipeline feature not working properly and deny/blocks incoming HTTP requests

### ISSUE THREAD

**Issue by CnApTaK** [nanoexpress/pro#39]
I have no idea where is the problem... (
![image](https://user-images.githubusercontent.com/1032312/74480373-7a89f800-4eb9-11ea-81a9-fff8c97d5b63.png)

**Comment by dalisoft** [comment]
According to [new rule](https://github.com/nanoexpress/pro/issues/44#issue-643407894), i keep issues open only if it's related to **nanoexpress**, not to it's core.
When it will be fixed on uWebSockets.js, then on this repo also will be fixed
