### ISSUE TITLE
nanoexpress [Server]: None of middleware will be called until you define route

### ISSUE THREAD

**Issue by gxdyxh** [nanoexpress/pro#40]
https://nanoexpress.js.org/routes/static-serve

Running the sample code prompts an error：nanoexpress [Server]: None of middleware will be called until you define route

**Comment by dalisoft** [comment]
Thanks for bug-report.
I don't think anyone will use only middlewares without routes for backend, so for optimizations this options was used.

As a workaround you can use `app.options(/'*', () => {});` and will work fine.

**Comment by dalisoft** [comment]
Updates documentation, updated **nanoexpress/middlewares** and this bug should be fixed.
Try out all latest packages/repos and you'll see performance boost and new features around bug-fixes
