### ISSUE TITLE
HTTP Route path SLASH support

### ISSUE THREAD

**Issue by BarryHoa** [nanoexpress/pro#41]
I use this example :
 https://github.com/nanoexpress/pro/blob/master/examples/route-example.js
with import app and route is:
```
const nanoexpress = require('nanoexpress-pro/cjs/nanoexpress');
const Route = require('nanoexpress-pro/cjs/Route');
```
Then the path` /` run ok
but the path `/foo `or` /foo/bar` return `{"code":404,"message":"The route does not exist"}`

node version : 12.16.3
npm 6.14.4

**Comment by dalisoft** [comment]
I'll look into this a bit more later (next week maybe), thanks for report

**Comment by dalisoft** [comment]
Use `/foo/bar/`, not `/foo/bar`.

**Comment by dalisoft** [comment]
As described [here](https://github.com/nanoexpress/pro/issues/44#issue-643407894), issue should not exist on uWebSockets.js, but this issue exists on uWebSockets.js, so i'll close this issue

**Comment by dalisoft** [comment]
Seems i fixed it wrong.

Read [here](https://github.com/uNetworking/uWebSockets.js/issues/336), [here](https://github.com/uNetworking/uWebSockets/issues/1049#issuecomment-626508774) and [here](https://stackoverflow.com/questions/5948659/when-should-i-use-a-trailing-slash-in-my-url) for more information.

Starting at **v2.1.0** this behavior will be revert back to correct solution, no auto slash
