### ISSUE TITLE
Empty body crashes application

### ISSUE THREAD

**Issue by d3v0e** [nanoexpress/pro#48]
If you send a POST request with an empty request body, it causes the application to crash with an error

`req.body = buffer.toString('utf8').replace(SPACE_TRIM_REGEX, '');
TypeError: Cannot read property 'toString' of undefined`

My way to fix this
`req.body = buffer ? buffer.toString('utf8').replace(SPACE_TRIM_REGEX, '') : null;`

**Comment by dalisoft** [comment]
PR is welcome.
Thanks for report

**Comment by dalisoft** [comment]
No PR.
As library provided as-is, currently no-support
