### ISSUE TITLE
req.body is undefined on patch requests

### ISSUE THREAD

**Issue by kran6a** [nanoexpress/pro#62]
### Is you/your team sponsoring this project

- [ ] Yes
- [X] No

### Minimal reproducible repo

https://github.com/kran6a/nanoexpress-bug-report

### Current Behavior

req.body property is undefined on patch routes.

To test the route I used the following curl command: `curl --request PATCH \
  --url http://127.0.0.1:3030/ \
  --header 'content-type: application/json' \
  --data '{
	"id": 1
}'`

The route works as expected with other HTTP verbs

### Expected behavior/code

req.body should work on patch routes the same way it works for all other methods

### Environment

- Node/npm version: Node 14.5.0/npm 6.14.5
- OS: Debian

**Comment by dalisoft** [comment]
Thanks for bug-report.

PR is welcome.
